# XDebug Generic
xdebug_output_dir: /tmp
xdebug_trigger_value:

# XDebug Remote Debugging
xdebug_mode: 'off'
xdebug_start_with_request: 'no'
xdebug_discover_client_host: 0
xdebug_client_host: localhost
xdebug_client_port: 9003
xdebug_log: /tmp/xdebug.log
xdebug_idekey: XDEBUG
xdebug_max_nesting_level: 200

# XDebug Display Settings
xdebug_force_display_errors: 0
xdebug_force_error_reporting: 0
xdebug_scream: 0
xdebug_var_display_max_children: 128
xdebug_var_display_max_data: 512
xdebug_var_display_max_depth: 3

# XDebug Function/Stack Traces
xdebug_collect_assignments: 0
xdebug_collect_return: 0
xdebug_show_exception_trace: 0
xdebug_show_local_vars: 0
xdebug_trace_format: 0
xdebug_trace_options: 0
xdebug_trace_output_name: trace.%c

# XDebug Profiler
xdebug_profiler_append: 0
xdebug_profiler_output_name: cachegrind.out.%p
