---
- name: "Setup composer authentications - {{ site }}"
  composer:
    command: config
    arguments: --auth http-basic.{{ composer_authentication.hostname }} {{ composer_authentication.username }} {{ composer_authentication.password }}
    working_dir: "{{ working_dir }}"
  no_log: true
  changed_when: false
  when:
    - not (not composer_authentication.hostname)
    - not (not composer_authentication.username)
    - not (not composer_authentication.password)
  loop: "{{ composer_authentications | default([]) }}"
  loop_control:
    loop_var: composer_authentication
    label: "{{ composer_authentication.hostname }}"
