---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
          cache-dependency-path: site/web/app/themes/abundanthousingma/yarn.lock

      - run: cd site/web/app/themes/abundanthousingma && yarn
      - run: cd site/web/app/themes/abundanthousingma && yarn build
      - run: cd site/web/app/themes/abundanthousingma && yarn test

  deploy:
    # Require that these jobs succeed before this one
    needs:
      - lint

    # Only deploy the main branch
    if: github.ref == 'refs/heads/main'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # The GitHub Environment to use
    environment: production

    steps:
      - uses: actions/checkout@v3

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.TRELLIS_DEPLOY_SSH_KNOWN_HOSTS }}

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
          ssh-auth-sock: ${{ github.workspace }}/ssh-auth.sock

      - uses: roots/setup-trellis-cli@v1
        with:
          ansible-vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

      - name: Deploy
        run: trellis deploy production
